[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient
    adafruit/Adafruit SHT31 Library
    bblanchon/ArduinoJson
    https://github.com/sparkfun/SparkFun_AS7343_Arduino_Library.git